services:
  owrx_antenna_manager:
    image: owrx_devices_status
    build: .
    container_name: owrx_devices_status
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
#    environment:
#      - MQTT_BROKER_URL=
#      - MQTT_BROKER_PORT=
#      - MQTT_USERNAME=
#      - MQTT_PASSWORD=
#      - OWRX_RECEIVER_URL=http://localhost:8073/status.json
#      - MQTT_TOPIC_DEVICE_STATUS=openwebrx/RX